### ISSUE TITLE
After update from 1.2.0 to 1.2.2 I started getting Javascript error and animations do not work

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/neon-animation#170]
In 1.2.1 you have updated web-animation-js version used from 2.1.4 to 2.2.0
https://github.com/PolymerElements/neon-animation/commit/8921a788d1a3e646b250b63c40f85546e4bfb44c

Now I see these errors in browser console:
```
web-animations-min.js line 15
TypeError: b.animate is not a function. 
(In 'b.animate({opacity:["1","0"]},{duration:1,fill:"forwards"})', 'b.animate' is undefined)
```
and a dialog - which was using animations - is not opening at all
`ReferenceError: Can't find variable: KeyframeEffect`

This error appears only in Safari (on iPhone and on my Mac in Safari 8.0). In Chrome everything is OK.
I'm not sure - is it problem in neon-animation or in web-animation-js so reported both here and there https://github.com/web-animations/web-animations-js/issues/73

**Comment by ellenaua** [comment]
You can try opening this page in Safari
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
  <base href="//polygit.org/components/">
  <link rel="import" href="polymer/polymer.html">
  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="paper-dialog/paper-dialog.html">
  <link rel="import" href="paper-button/paper-button.html">
  
  <dom-module id="my-component">
    <style>
      h1{color: red}
      paper-dialog{
        padding: 30px;
      }
    </style>
    <template>
      <paper-dialog id="dialog" with-backdrop>
        Dialog contents
      </paper-dialog>
      <paper-button raised on-click="_openDialog">Open dialog</paper-button>
    </template>

    <script>
        (function() {
            'use strict';
            Polymer({
                is: 'my-component',
                _openDialog(n) {
                  this.$.dialog.open();
                }
            })
        })()
    </script>
</dom-module>
  
</head>
<body>
  <my-component></my-component>
</body>
</html>
```

**Comment by samuelli** [comment]
Thanks for the report @ellenaua. I created a[ test JSBin](http://jsbin.com/qahesulije/1/edit?html,console,output) using your provided test case and had to make a few changes (swap the import lines and use `HTMLImports.whenReady()`).

With that I was unable to reproduce your bug on Safari 9.1. Can you check using that linked JSBin please?

**Comment by panuhorsmalahti** [comment]
I get a similar error on Firefox:
```javascript
TypeError: b.animate is not a function
```

Works fine in Chrome.

For some reason the animations work in the Polymer paper-dialog demo page, though.

**Comment by dstockwell** [comment]
Let's track this over in https://github.com/web-animations/web-animations-js/issues/73

Please provide and live page (eg. jsbin) and the exact browser/device configuration you are using.
